# Generated by Django 5.1.7 on 2025-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'เสื้อเชิ้ต'), ('SU', 'ชุดสูท'), ('T', 'เสื้อท็อป'), ('D', 'ชุดเดรส'), ('C', 'เสื้อคาร์ดิแกน'), ('J', 'กางเกงยีนส์'), ('SK', 'กระโปรง'), ('SW', 'ชุดว่ายน้ำ'), ('B', 'เบลเซอร์'), ('JK', 'แจ็คเก็ต'), ('H', 'เสื้อฮู้ด'), ('SO', 'ถุงเท้า'), ('HA', 'เครื่องประดับผม'), ('SC', 'ผ้าพันคอ'), ('HT', 'หมวก'), ('BE', 'เข็มขัด'), ('SG', 'แว่นกันแดด'), ('BA', 'กระเป๋า')], max_length=2),
        ),
    ]
