# Generated by Django 5.1.7 on 2025-03-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('S', 'Shirts'), ('SU', 'Suits'), ('T', 'Tops'), ('D', 'Dresses'), ('C', 'Cardigans'), ('J', 'Jeans'), ('SK', 'Skirts'), ('SW', 'Swimwear'), ('B', 'Blazers'), ('JK', 'Jackets'), ('H', 'Hoodies'), ('SO', 'Socks'), ('HA', 'Hair Accessories'), ('SC', 'Scarves'), ('HT', 'Hats'), ('BE', 'Belts'), ('SG', 'Sunglasses'), ('BA', 'Bags')], max_length=2)),
                ('image', models.ImageField(upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('zip', models.IntegerField()),
                ('state', models.CharField(choices=[('BKK', 'Bangkok'), ('CNX', 'Chiang Mai'), ('CHI', 'Chiang Rai'), ('KBI', 'Krabi'), ('LPG', 'Lampang'), ('LPN', 'Lopburi'), ('NPT', 'Nakhon Pathom'), ('NRT', 'Nakhon Ratchasima'), ('NRN', 'Nakhon Si Thammarat'), ('PBI', 'Phetchaburi'), ('PHU', 'Phuket'), ('PKT', 'Phayao'), ('PCH', 'Prachuap Khiri Khan'), ('RBR', 'Ratchaburi'), ('SGK', 'Samut Prakan'), ('SRT', 'Surat Thani'), ('UDN', 'Udon Thani'), ('UBN', 'Ubon Ratchathani'), ('YLA', 'Yala')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
    ]
