# Generated by Django 5.1.7 on 2025-03-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
