# Generated by Django 5.1.7 on 2025-04-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_zip_customer_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='item',
        ),
    ]
