# Generated by Django 5.1.7 on 2025-04-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('BKK', 'Bangkok'), ('CNX', 'Chiang Mai'), ('CHI', 'Chiang Rai'), ('KBI', 'Krabi'), ('LPG', 'Lampang'), ('LPN', 'Lopburi'), ('NPT', 'Nakhon Pathom'), ('NRT', 'Nakhon Ratchasima'), ('NRN', 'Nakhon Si Thammarat'), ('PBI', 'Phetchaburi'), ('PHU', 'Phuket'), ('PKT', 'Phayao'), ('PCH', 'Prachuap Khiri Khan'), ('RBR', 'Ratchaburi'), ('SGK', 'Samut Prakan'), ('SRT', 'Surat Thani'), ('UDN', 'Udon Thani'), ('UBN', 'Ubon Ratchathani'), ('YLA', 'Yala')], max_length=100),
        ),
    ]
